workflows:
  android-release:
    name: Android Release Build
    max_build_duration: 60
    instance_type: mac_mini_m1

    environment:
      java: 17

    scripts:
      - name: Build APK
        script: |
          chmod +x ./gradlew
          ./gradlew assembleRelease

    artifacts:
      - app/build/outputs/apk/release/*.apk
